import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import TopNavBar from '@/components/nav/top-nav-bar';

import { Providers } from './providers';
import { getLoggedInUser } from '@/actions/authActions';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<TopNavBar isUserLoggedIn={false} />
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
